name: CI

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@master
      with:
        node-version: 10.x
    - run: npm install
    - run: npm run pack
    - name: Publish
      env:
        AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        NPM_AUTH_TOKEN: '${{ secrets.NPM_AUTH_TOKEN }}'
      run: cp .npmrc.template ~/.npmrc && npm publish
